name: Polymarket Price Alert

on:
  workflow_dispatch:   # ← keep this, no inputs required

permissions:
  contents: write

concurrency:
  group: price-alert
  cancel-in-progress: true

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files (debug)
        run: ls -R

      - uses: actions/cache/restore@v4
        with:
          path: alert_state.json
          key: alert_state-v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install deps
        run: pip install --quiet requests

      - name: Run price check
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: python polymarket_price.py

      - uses: actions/cache/save@v4
        with:
          path: alert_state.json
          key: alert_state-v1
